#!/usr/bin/perl

# Install me in cron!
# splunk logfile scraper watchdog
# 1,16,31,46 * * * * /opt/disys/noarch/watchloglog >/dev/null 2>&1 &

$host = `hostname -s`; chomp($host);
$conf = "/opt/disys/etc/loglog/$host.conf";

$loglog = "/opt/disys/noarch/loglog";
if ($host eq "comet1a") { $loglog .= "-test"; }

$ok = `ps -ef | grep watchloglog | grep -v grep | wc -l` + 0;
if ($ok > 1) { exit; }

while (1) { 
   $ok = `ps -ef | grep loglog | grep -v watchloglog | grep -v grep | wc -l` + 0; 
   if ($ok) { sleep(10); next; }
   if (-e $conf) { 
      system("$loglog &");
   }
}
